### ISSUE TITLE
Screenshot attract more eyeballs

### ISSUE THREAD

**Issue by hrchu** [gresrun/jesque-web#11]
Like this: https://github.com/stitchfix/resque-brain

**Comment by gresrun** [comment]
@hrchu Would you like to supply one? :wink:

**Comment by hrchu** [comment]
I will do a little bit later.

**Comment by hrchu** [comment]
Add some screenshots in wiki, feel free to edit it as you wish.

**Comment by gresrun** [comment]
Thanks!
